# Generated by Django 6.0.6 on 2026-06-18 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_add_public_id_to_item_and_want'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_by', to='exchange.item'),
        ),
        migrations.AlterField(
            model_name='want',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wants', to=settings.AUTH_USER_MODEL),
        ),
    ]
