# Generated by Django 6.0.6 on 2026-06-18 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_tradeproposal_tradeparticipant_tradeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
