# Generated by Django 6.0.6 on 2026-06-19 05:56

import django.db.models.deletion
import exchange.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_tradeitem_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=exchange.models.TradeCycle.default_cycle_expiry)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCycleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='exchange.tradecycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cycle', 'user'), name='unique_user_per_cycle')],
            },
        ),
        migrations.CreateModel(
            name='TradeCycleTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='exchange.tradecycle')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_items_given', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_records', to='exchange.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_items_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cycle', 'item'), name='unique_item_per_cycle')],
            },
        ),
    ]
