# Generated by Django 6.0.6 on 2026-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_tradecycle_tradecycleparticipant_tradecycletrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('TRADED', 'Traded')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
