# Generated by Django 6.0.6 on 2026-06-22 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_item_created_at_alter_item_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='exchange.tradeproposal')),
            ],
        ),
    ]
