# Generated by Django 6.0.6 on 2026-06-23 10:06

import exchange.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_tradeexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproposal',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=exchange.models.default_proposal_expiry),
        ),
    ]
