# Generated by Django 6.0.6 on 2026-06-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_item_deleted_at_item_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeproposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
